### ISSUE TITLE
Нужно больше российского вмешательства

### ISSUE THREAD

**Issue by airlambda** [Binney/conservativepartymanifesto#2]
Как мы не сделали главную страницу этого богом забытого веб-сайта всеми деньгами, которые мы напрямую вложили в руки этого блондинистого ребенка Джонсона? Кремль возмущен! Отчет об ошибке подан!

**Comment by Binney** [comment]
Извините, ваш комментарий не разрешен на этом этапе альфа-обзора. Пожалуйста, вернитесь, когда мы построим достаточное количество пилонов. Прощание.
